### ISSUE TITLE
Needs better error checking

### ISSUE THREAD

**Issue by tyldum** [tyldum/mojolicious-plugin-prometheus#19] opened 2019-07-23 17:56 UTC
https://github.com/tyldum/mojolicious-plugin-prometheus/blob/6d56d47162412e86f7bad684b5ac6abc83a777eb/lib/Mojolicious/Plugin/Prometheus.pm#L195

In one codebase using this plugin I observe this: `IPC::ShareLite fetch() error: Invalid argument`
Now the real problem is most likely somewhere in the codedebase, but this still needs a better handling.

**Comment by RastislavHudak** [comment] 2020-11-11 11:21
Do you have any pointers on what can be causing this? I tried with minimal mojo and mojo lite apps and it did not happened, but in a larger app it starts happening after cca 1hr and then it's broken until restart.

**Comment by tyldum** [comment] 2020-11-11 15:55
Only observed it in a service that was unused for weeks. Once in active use, we haven't seen it.

**Comment by christopherraa** [comment] 2022-02-21 17:30
@RastislavHudak Have you observed this recently? I have not been able to find any instances of this happening at `$work`, but all our services have a fairly consistent traffic. If you are somehow able to reproduce this issue then step-by-step instructions would be very much appreciated as that would mean I could start looking into it.

**Comment by RastislavHudak** [comment] 2022-03-03 11:50
I haven't because I've uninstalled the module to prevent the API from crashing. The step-by-step instruction would be easy: I've simply queried the metrics every 5 minutes or so (without anything else happening) until it crashed, but as I wrote, it did not occur with minimal mojolicious installation, so probably it collides with some other module/plugin. The list of modules I am using is following, if it helps:

```
Mojolicious@8.63
Mojolicious::Plugin::Database
Mojolicious::Plugin::Session
Mojolicious::Plugin::CHI
Mojolicious::Plugin::I18N
Mojolicious::Plugin::Authentication
Mojolicious::Plugin::Log::Any
Mojolicious::Plugin::Prometheus
MongoDB@1.8.3
Net::LDAPS
IO::Socket::SSL
IO::Scalar
Sereal
Crypt::CBC
Crypt::Rijndael
Crypt::URandom
Math::Random::ISAAC::XS
MIME::Base64
Switch
Log::Log4perl
Log::Dispatch::FileRotate
LWP::UserAgent::Determined
File::MimeInfo::Magic
XML::Writer
XML::SAX
XML::LibXML
XML::Parser
XML::Parser::PerlSAX
XML::XPath
SOAP::Lite
DBD::mysql
Data::MessagePack
DateTime
DateTime::Format::ISO8601
Clone
File::Find::utf8
MIME::Lite
MIME::Lite::TT::HTML
Storable
```
where the CHI driver is [Memory](https://github.com/phaidra/phaidra-api/blob/master/PhaidraAPI.pm#L98), that's about the only thing that looks to me like it can maybe interfere with the shared memory or something.

**Comment by christopherraa** [comment] 2023-11-02 19:55
Okay, so I'm closing this issue now due to not being able to reproduce it at all or observing it in production at `$work` throughout the time we've been using this module. Feel free to reopen if someone can reproduce this issue reliably. In that case I will look into it and see if I can find a fix.

**Closed as completed by christopherraa** 2023-11-02 19:55 UTC
